version: '3'
services:
  apache:
    image: php:7.2-apache
    container_name: ApachePHP_PHP
    ports:
      - 8080:80
    volumes:
      - $PWD:/var/www/html/
    networks:
      lan:
        ipv4_address: 172.0.0.2
    environment:
      - APP_NAME=root
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: MySQL_PHP
    ports:
      - 3306:3306
    volumes:
      - $PWD/db_backup:/var/lib/mysql
    networks:
      lan:
        ipv4_address: 172.0.0.3
    environment:
      MYSQL_ROOT_PASSWORD: root1

networks:
  lan:
    ipam:
      driver: default
      config:
        - subnet: 172.0.0.0/16

